// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSystemMVC.Data;

#nullable disable

namespace ReservationSystemMVC.Migrations
{
    [DbContext(typeof(ReservationSystemMVCContext))]
    [Migration("20240209114458_RoomEquipmentManyToMany")]
    partial class RoomEquipmentManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystemMVC.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("ExtraBedAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.RoomEquipment", b =>
                {
                    b.Property<int>("RoomEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomEquipmentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomEquipmentId");

                    b.ToTable("RoomEquipment");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.RoomRoomEquipment", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("RoomEquipmentId")
                        .HasColumnType("int");

                    b.HasKey("RoomId", "RoomEquipmentId");

                    b.HasIndex("RoomEquipmentId");

                    b.ToTable("RoomRoomEquipment");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.Room", b =>
                {
                    b.HasOne("ReservationSystemMVC.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.RoomRoomEquipment", b =>
                {
                    b.HasOne("ReservationSystemMVC.Models.RoomEquipment", "RoomEquipment")
                        .WithMany("RoomRoomEquipments")
                        .HasForeignKey("RoomEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationSystemMVC.Models.Room", "Room")
                        .WithMany("RoomRoomEquipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("RoomEquipment");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.Room", b =>
                {
                    b.Navigation("RoomRoomEquipments");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.RoomEquipment", b =>
                {
                    b.Navigation("RoomRoomEquipments");
                });

            modelBuilder.Entity("ReservationSystemMVC.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
